#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanTimeDirectories
rm -r log.*

# if [ "$(ls -A SVD)" ]; 
#     then
#     rm -r SVD/*
# 	else
#     echo "SVD is Empty"
# fi

#------------------------------------------------------------------------------
