#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication $(getApplication)

touch Blocks.foam

# if true
# then
#     runApplication foamToEnsight -noZero
#     runApplication foamToVTK
# fi

#------------------------------------------------------------------------------
