#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

# runApplication ansysToFoam \
#     ${FOAM_TUTORIALS:?}/resources/geometry/flange.ans -scale 0.001

# m4 system/blockMeshDict.m4 > system/blockMeshDict
# runApplication blockMesh
runApplication $(getApplication)

touch svdtest.foam

# if true
# then
#     runApplication foamToEnsight -noZero
#     runApplication foamToVTK
# fi

#------------------------------------------------------------------------------
